buildscript {
    ext {
        compileSdk = 36
        minSdk = 34
        targetSdk = 36
        versionCode = 1036
        versionName = "1.0.36"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.7.0"
    }
}

allprojects {
    repositories {
        // ✅ KOSONGKAN — sudah dideklarasikan di settings.gradle
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
