android {
    namespace "com.solely.browser"
    compileSdk 36

    defaultConfig {
        applicationId "com.solely.browser"
        minSdk 34
        targetSdk 36
        versionCode 1036
        versionName "1.0.36"
    }

    signingConfigs {
        release {
            storeFile file(project.hasProperty('keystoreFile') ? project.keystoreFile : "debug.keystore")
            storePassword project.hasProperty('keystorePassword') ? project.keystorePassword : "android"
            keyAlias project.hasProperty('keyAlias') ? project.keyAlias : "androiddebugkey"
            keyPassword project.hasProperty('keyPassword') ? project.keyPassword : "android"
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
}
