name: Build & Release Solely Browser
run-name: SoleyB 🚀 ${{ github.ref_name }}

on:
  push:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set Execute Permission
        run: chmod +x gradlew

      # ✅ TANPA KUNCI / TANPA RAHASIA — langsung build
      - name: Build Release APK
        run: ./gradlew assembleRelease --no-daemon

      - name: Show APK Location
        run: find . -name "*.apk" -type f

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SolelyBrowser-v1.0.36
          path: app/build/outputs/apk/release/*.apk
